language: java

jdk: -openjdk8 

addons:
  sonarcloud:
    organization: "pippopaperino"
    token:
      secure: "jWzNRyUZL54yHjJ0+Pfq1JQPBTMRRaAXEhOQ5kAPwkCjI6Ibq7Fo1JaX9Dsp9qyaiPkpsKasAZiF2+3DPWjSilhVXiM39hkP003OpaNnet2m+E5/WDWHSsJ13J7FYvBX1lt5ldLzqixAYndhfTZFDKtRVDy7WTZ2Bm8/V01jwdo05el0nhtJ4HW4X09J+PyqrsW9rlulYBNtYNFgiebqosHeuGM5MglT9jhyiCZERo3EZxrgkFn/tUT8f+Fv0309A/ZFzc9Ll35y6t/KxWtd2Wr9KYe9dScOLhS1mbUklrl9oPMj302ilNdxM5C8jvfQdoAZI55HtFiEkFZplJgHu0d8QyB/LoKB34Biz4bpsvnzTACegpOKnM439IqjfX0w9xEBPJjwDKI0+L1BImuVQAh207fnVQ7X5teitLPvSX5+UCkdl/3ImeX0l53lrbHdlJ+KnJXtPvwGtdmchd1p84/tubkgCMNUSNFj1q3iHweCeNBYJVI6c7s7v/jJVSsnb2agNs/GDDvByM885lEGaAK9xEyZ/FYfoAVLK9bnYYiRc4FHKfpWvkC7Cy180aGRHv93JHTUHmTcs7ffdRjXpQKwZXA85oXKBLYOMfGIQVp2Bs4wcITo53/4VCgmieY8M+IC8Y8mbHd5lt4oveImtas52rnBZWLoLW8V+4hIR5s="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -U -Dtest=BookKeeperCreateLedgerTest -DfailIfNoTests=false clean verify -e org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Capo80_bookkeeper

